apiVersion: release-notes/v2
kind: feature
area: installation
issues:
  - 30393
  - 42792

releaseNotes:
- |
  **Added** Allow for re-executions of istio-init container by running a preemtive cleanup beforehand
