apiVersion: release-notes/v2
kind: feature
area: traffic-management
issue:
- 54726
releaseNotes:
- |
  **Improved** The CNI agent to no longer require `hostNetwork`, improving compatibility. Dynamic switching to the host network is now performed whenever necessary.
  The feature is opt-in and can be enabled by setting `ambient.shareHostNetworkNamespace` field to `false` in the `istio-cni` chart. This feature will be enabled by default in Istio 1.26.