apiVersion: release-notes/v2
kind: feature
area: security
releaseNotes:
- |
  **Updated** default value of the feature flag `ENABLE_AUTO_ENHANCED_RESOURCE_SCOPING` to true.
upgradeNotes:
- title: Default value of the feature flag `ENHANCED_RESOURCE_SCOPING` to true
  content: |
    `ENHANCED_RESOURCE_SCOPING` is enabled by default. This means that meshConfig.discoverySelectors
    will limit the CustomResource configurations that can be processed by pilot.
    root-ca certificate distribution is also affected.

    If this is not desired, use the new `compatibilityVersion` feature to fallback to old behavior.

